<a href="https://colab.research.google.com/github/PedroHenriquesDev/Exercicios-Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])

print(pecas_vendidas)

[150 120  90 210 300 250 180]


In [3]:
faturamento = pecas_vendidas * 50

print(faturamento)

[ 7500  6000  4500 10500 15000 12500  9000]


In [5]:
mascara = pecas_vendidas > 200

print(mascara)

[False False False  True  True  True False]


In [6]:
dias_pico = pecas_vendidas[mascara]

print(dias_pico)

[210 300 250]


In [7]:
print(pecas_vendidas[pecas_vendidas > 200])

[210 300 250]


In [8]:
vendas = np.array([
    [200, 220, np.nan, 250],
    [150, 180, 160, 190],
    [300, 310, 290, 330]
])

print(vendas)

[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]


In [9]:
total_lojas = np.sum(vendas, axis=1)

print(total_lojas)

[  nan  680. 1230.]


In [10]:
total_lojas = np.nansum(vendas, axis=1)

print(total_lojas)

[ 670.  680. 1230.]


In [12]:
media_geral = np.nanmean(vendas)

print(media_geral)

234.54545454545453


In [13]:
print(f"Média diária geral: {media_geral:.2f}")

Média diária geral: 234.55


In [14]:
meta = 200

In [15]:
resultado_meta = np.where(
    vendas >= meta,
    "Meta Atingida",
    "Abaixo"
)

print(resultado_meta)

[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


In [16]:
rng = np.random.default_rng(42)

In [17]:
categorias = np.array([
    "Eletrônicos",
    "Roupas",
    "Casa"
])

In [18]:
vendas_categorias = rng.choice(
    categorias,
    size=50
)

print(vendas_categorias)

['Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Casa' 'Casa' 'Casa'
 'Casa' 'Roupas' 'Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas'
 'Eletrônicos' 'Casa' 'Casa' 'Roupas' 'Roupas' 'Casa' 'Roupas' 'Roupas'
 'Roupas' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Eletrônicos' 'Casa'
 'Casa' 'Eletrônicos' 'Roupas' 'Eletrônicos' 'Casa' 'Casa' 'Roupas'
 'Eletrônicos' 'Casa' 'Roupas' 'Casa' 'Casa' 'Casa']


In [19]:
categorias_unicas, quantidades = np.unique(
    vendas_categorias,
    return_counts=True
)

print(categorias_unicas)
print(quantidades)

['Casa' 'Eletrônicos' 'Roupas']
[21 12 17]


In [20]:
for categoria, quantidade in zip(categorias_unicas, quantidades):
    print(categoria, ":", quantidade)

Casa : 21
Eletrônicos : 12
Roupas : 17


In [21]:
faturamento_campanhas = np.array([
    12000,
    45000,
    23000,
    89000,
    31000
])

In [22]:
indice_campeao = np.argmax(faturamento_campanhas)

print(indice_campeao)

3


In [23]:
print(faturamento_campanhas[indice_campeao])

89000


# Segunda atividade — Organização e Transformação

In [24]:
dias = np.arange(1, 31)

print(dias)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [25]:
metas = np.linspace(20000, 30000, 5)

print(metas)

[20000. 22500. 25000. 27500. 30000.]


In [26]:
estoque = np.array([10.5, 20.1, 30.9])

estoque_inteiro = estoque.astype(int)

print(estoque_inteiro)

[10 20 30]


In [27]:
ultimos_dias = dias[-5:]

print(ultimos_dias)

[26 27 28 29 30]


In [28]:
ultimos_dias_invertidos = dias[-5:][::-1]

print(ultimos_dias_invertidos)

[30 29 28 27 26]


In [29]:
visitas = np.array([
    1000, 1200, 1500,
    1300, 1400, 1600,
    1700, 1800, 2000,
    2100, 2200, 2500
])

In [30]:
visitas_trimestres = visitas.reshape(4, 3)

print(visitas_trimestres)

[[1000 1200 1500]
 [1300 1400 1600]
 [1700 1800 2000]
 [2100 2200 2500]]


In [31]:
primeiro_semestre = np.array([
    [1000, 1200, 1500],
    [1300, 1400, 1600]
])

segundo_semestre = np.array([
    [1700, 1800, 2000],
    [2100, 2200, 2500]
])

In [32]:
ano = np.vstack([
    primeiro_semestre,
    segundo_semestre
])

print(ano)

[[1000 1200 1500]
 [1300 1400 1600]
 [1700 1800 2000]
 [2100 2200 2500]]


In [33]:
primeiro_trimestre = ano[0].copy()

print(primeiro_trimestre)

[1000 1200 1500]


In [35]:
primeiro_trimestre[0] = 9999

print(primeiro_trimestre)
print(ano)

[9999 1200 1500]
[[1000 1200 1500]
 [1300 1400 1600]
 [1700 1800 2000]
 [2100 2200 2500]]


In [36]:
dados_achatados = ano.ravel()

print(dados_achatados)

[1000 1200 1500 1300 1400 1600 1700 1800 2000 2100 2200 2500]


In [37]:
notas = np.array([85, 92, 78, 95, 88])

In [38]:
ranking = np.argsort(notas)

print(ranking)

[2 0 4 1 3]


In [39]:
ranking_decrescente = np.argsort(notas)[::-1]

print(ranking_decrescente)

[3 1 4 0 2]


In [40]:
precos = np.array([100, 200, 300])

In [41]:
print(precos.shape)

(3,)


In [42]:
precos_coluna = precos[:, np.newaxis]

print(precos_coluna)
print(precos_coluna.shape)

[[100]
 [200]
 [300]]
(3, 1)


In [43]:
descontos = np.array([0.10, 0.20, 0.30])

In [44]:
precos_com_desconto = precos_coluna * (1 - descontos)

print(precos_com_desconto)

[[ 90.  80.  70.]
 [180. 160. 140.]
 [270. 240. 210.]]
